# Shell variables
# Generated by 'wal'
wallpaper="~/Pictures/Wallpaper/blue.jpg"

# Special
background='#1e281e'
foreground='#dcddcf'
cursor='#dcddcf'

# Colors
color0='#1e281e'
color1='#699599'
color2='#6D9BA5'
color3='#78A6AB'
color4='#7FA9C1'
color5='#A3AF93'
color6='#87AFB3'
color7='#dcddcf'
color8='#9a9a90'
color9='#699599'
color10='#6D9BA5'
color11='#78A6AB'
color12='#7FA9C1'
color13='#A3AF93'
color14='#87AFB3'
color15='#dcddcf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
